export default [
  {
    name: 'MELT',
    img: 'img/melt.jpg',
    entry: 'projects/melt/dist/index.html',
    public: ['projects/melt/dist'],
    route: 'melt',
  },
  {
    name: 'FLUX',
    img: 'img/flux.jpg',
    entry: 'projects/flux/out/index.html',
    public: ['projects/flux/out'],
    route: 'flux',
  },
  {
    name: 'MA',
    img: 'img/ma.jpg',
    route: 'ma/index.html',
  },
  {
    name: 'WIFI SOUNDSCAPES',
    img: 'img/wifi-soundscapes.jpg',
    route: 'wifi-soundscapes/index.html',
  },
  {
    name: 'ALCHEMY PAINTER',
    img: 'img/alchemy-painter.jpg',
    route: 'https://sidequestvr.com/#/app/226',
  },
  {
    name: 'MONSTER WITHIN',
    img: 'img/monster-within.jpg',
    route: 'monster-within.html',
  },
  {
    name: 'THREE BODY',
    img: 'img/three-body.jpg',
    entry: 'projects/three-body/dist/index.html',
    public: ['projects/three-body/dist'],
    route: 'three-body',
  },
  {
    name: 'MONSTER OR FRIEND',
    img: 'img/monster-or-friend.jpg',
    entry: 'projects/monster-or-friend/dist/index.html',
    public: ['projects/monster-or-friend/dist'],
    route: 'monster-or-friend',
  },
  {
    name: 'AI ANIMATION',
    img: 'img/ai-animation.jpg',
    entry: 'projects/ai-animation/build/index.html',
    public: ['projects/ai-animation/build'],
    route: 'ai-animation',
  },
  {
    name: 'GENDERGRAPH',
    img: 'img/gendergraph.jpg',
    entry: 'projects/gender-graph/public/html/index.html',
    public: ['projects/gender-graph/public'],
    route: 'gendergraph',
  },
  {
    name: 'STARLING SIMULATION',
    img: 'img/starling.jpg',
    route: 'https://starlingstorage.io/',
  },
  {
    name: 'PROCEDURAL IK CRAWLER',
    img: 'img/procedural-ik.png',
    entry: 'projects/procedural-ik-crawler/build/index.html',
    public: ['projects/procedural-ik-crawler/build'],
    route: 'procedural-ik-crawler',
  },
  {
    name: 'ANTICAP',
    img: 'img/anticap.jpg',
    route: 'https://github.com/Kif11/anticap',
  },
  {
    name: 'STREET SOUNDS',
    img: 'img/street-sonds.jpg',
    route: 'street-sounds',
  },
  {
    name: 'RELAXATION ROOM',
    img: 'img/relaxation-room.jpg',
    entry: 'projects/relaxation-room/build/index.html',
    public: ['projects/relaxation-room/build'],
    route: 'relaxation-room',
  },
  {
    name: 'BOX PROJECTED ENVIRONMENT MAPPING',
    img: 'img/bpcem.jpg',
    route:
      'https://threejs.org/examples/?q=envm#webgl_materials_envmaps_parallax',
  },
  {
    name: 'GALACTIC GYPSY',
    img: 'img/galactic-gypsy.jpg',
    entry: 'projects/galactic-gypsy/build/index.html',
    public: ['projects/galactic-gypsy/build'],
    route: 'galactic-gypsy',
  },
  {
    name: 'SKINNED MESH IK',
    img: 'img/skinned-mesh-ik.jpg',
    route: 'https://jsantell.github.io/THREE.IK/examples/#skinned-mesh',
  },
  {
    name: 'GROW YOUR OWN BOT',
    img: 'img/creatures.jpg',
    entry: 'projects/grow-your-own-bot/build/index.html',
    public: ['projects/grow-your-own-bot/build'],
    route: 'grow-your-own-bot',
  },
  {
    name: 'NEUROJAM',
    img: 'img/neurojam.jpg',
    entry: 'projects/neurojam-ui/out/index.html',
    public: ['projects/neurojam-ui/out'],
    route: 'neurojam',
  },
  {
    name: 'AR GPU PARTICLES',
    img: 'img/ar-gpu-particles.jpg',
    entry: 'projects/AR-GPU-Particles/build/index.html',
    public: ['projects/AR-GPU-Particles/build'],
    route: 'ar-gpu-particles',
  },
  {
    name: 'AURACARIA DREAMS',
    img: 'img/auracaria-dreams.jpg',
    entry: 'projects/auracaria-dreams/public/html/mary.html',
    public: ['projects/auracaria-dreams/public'],
    route: 'auracaria-dreams',
  },
  {
    name: 'THREEJS CURVATURE',
    img: 'img/curvatureExample.jpg',
    route: 'https://threejs.org/examples/#webgl_materials_curvature',
  },
  {
    name: '3D TSP HEART',
    img: 'img/tsp-3d-art.jpg ',
    entry: 'projects/tsp-3D-art/public/html/final.html',
    public: ['projects/tsp-3D-art/public'],
    route: 'tsp-3D-art',
  },
  {
    name: '360 PHOTO TO VIDEO',
    img: 'img/360photo-to-video.jpg',
    entry: 'projects/360-photo-to-video/public/html/index.html',
    public: ['projects/360-photo-to-video/public'],
    route: '360-photo-to-video',
  },
  {
    name: 'VERTEX CACHE',
    img: 'img/vertex-cache.jpg',
    entry: 'projects/vertex-texture-cache/public/html/index.html',
    public: ['projects/vertex-texture-cache/public'],
    route: 'vertex-cache',
  },
  {
    name: 'WHIRPOOLS',
    img: 'img/whirpools.jpg ',
    route: 'whirlpools.html',
  },
  {
    name: 'PHOTOSPHERES',
    img: 'img/photospheres.jpg ',
    route: 'photospheres.html',
  },
  {
    name: 'TERMINAL PRINTS',
    img: 'img/terminal-prints.jpg',
    route: 'terminal-prints.html',
  },
];